/*******************************************************************************
 *                                                                             *
 * This font definition file is generated by FontGen v2.00                     *
 *              by Bahri Okuroglu - bahrio@yahoo.com                           *
 *                                                                             *
 * Make sure it is legal to use installed fonts on your PC for this conversion *
 *                                                                             *
 * Font definition for MS Sans Serif 8 
 *          bold:y 
 *          italic:n 
 *          underline:n 
 *          strikeout:n 
 *          direction:0 
 *          compressed:n 
 *          flip X: n 
 *          flip Y: n 
 *                                                                             *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' *
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,       *
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR      *
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR          *
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,       *
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,         *
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; *
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,    *
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR     *
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF      *
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE                                   *
 *******************************************************************************/


#ifndef FONTGEN_FTYPES
#define FONTGEN_FTYPES

#define FONTGEN_USE_MAPPING_TABLE 
#define FONTGEN_USE_PRECALCULATED_OFFSETS 

/* Following type definition is only used for compressed font definitions.
   In the compressed mode, the leading and trailing empty lines are removed
   from the glyph defition. The number of the removed lines from top and
   the bottom is given with the following type.

   Please notice that the compression is performed before rotation, so that
   if the font is rotated 90 degrees than there may be leading empty rows in the
   produced definition, but not empty columns.
 */
typedef struct GLYPH_DET {
   unsigned char leading;     /* the number of lines removed from the top of the char    */
   unsigned char trailing;    /* the number of lines removed from the bottom of the char */
} GLYPH_DET;
   


typedef struct FONT_DEF {
   unsigned char glyph_width;                 /* glyph width in pixels              */
                                              /*     0 for variable width fonts     */
   unsigned char glyph_height;                /* glyph height for storage           */
   unsigned char code *glyph_table;           /* font table start address in memory */
   unsigned char code *mapping_table;         /* used to find the index of a glyph  */
   unsigned char code *width_table;           /* width table start adress           */
                                              /*        NULL for fixed width fonts  */
   unsigned int code *offset_table;           /* keeps the offsets of the first byte*/
                                              /*                      of each glyph */
   GLYPH_DET code *detail_table;              /* NULL for uncompressed fonts        */
   unsigned char vertical;                    /* 0: for 0/180 degrees, 1 for 90/270 */
} FONT_DEF;
#endif


extern struct FONT_DEF code MS_Sans_Serif_8_n_bnnn_0_n;